# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1erNyVkbS7BQ-nAbA1W-Axc_al91jmHQs
"""

def my_first_chatbot():
    print("البوت:اهلا بك كيف يمكنني مساعدتك؟")
    while True:
      user_input=input(" انت:")
      if"مرحبا" in user_input or "اهلا" in user_input:
            print("البوت:مرحبا بك يسعدني التحدث معك")
      elif"اسمك" in user_input:
            print("البوت:انا اسمي بوت الذكاء الاصطناعي الخاص بك")
      elif"بايثون" in user_input:
          print("البوت:بايثون هي لغه برمجه مهمه ")
      elif"سلام" in user_input or "خروج" in user_input:
          print("البوت:مع السلامه!")
          break
      else:
        print("البوت:عذرا! لم افهم هذه الكلمه بعد ،يمكنك تطوري لافهمها مستقبلا")
my_first_chatbot()